name: app
description: "A new Flutter project."
publish_to: "none"

version: 0.1.0+31

environment:
  sdk: ^3.9.2

dependencies:
  animate_do: ^4.2.0
  animated_bottom_navigation_bar: ^1.4.0
  animations: ^2.0.11
  auto_route: ^10.1.0+1
  bloc: ^9.0.1
  cached_network_image: ^3.4.1
  carousel_slider: ^5.1.1
  cupertino_icons: ^1.0.8
  custom_refresh_indicator: ^4.0.1
  daamduuqr_client:
    path: client
  dio: ^5.8.0+1
  equatable: ^2.0.7
  firebase_auth: ^6.1.1
  firebase_core: ^4.2.0
  firebase_messaging: ^16.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_dotenv: ^5.2.1
  flutter_local_notifications: ^19.5.0
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.6
  flutter_secure_storage: ^9.2.4
  flutter_spinkit: ^5.2.2
  flutter_svg: ^2.2.0
  flutter_tilt: ^3.3.2
  get_it: ^8.0.3
  google_sign_in: ^7.2.0
  group_button: ^5.3.4
  hive_ce: ^2.11.3
  hive_ce_flutter: ^2.3.1
  hydrated_bloc: ^10.1.1
  intl: ^0.20.2
  json_annotation: ^4.9.0
  mobile_scanner: ^7.0.1
  package_info_plus: ^9.0.0
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  share_plus: ^12.0.0
  shimmer: ^3.0.0
  sign_in_with_apple: ^7.0.1
  smooth_page_indicator: ^1.2.1
  story_view: ^0.16.6
  talker: ^5.0.1
  talker_bloc_logger: ^5.0.1
  talker_dio_logger: ^5.0.1
  talker_flutter: ^5.0.1
  talker_logger: ^5.0.1
  url_launcher: ^6.3.2
  uuid: ^4.5.1

dev_dependencies:
  auto_route_generator: ^10.2.3
  build: ^2.4.0
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.9.5
  lean_builder: ^0.1.0-alpha.13
  retrofit_generator: ^9.3.0

flutter_launcher_icons:
  android: "lc_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/icon/icon.png"
    background_color: "#ffffff"
    theme_color: "#ffffff"
  windows:
    generate: false
    image_path: "assets/icon/icon.png"
    icon_size: 48
  macos:
    generate: false
    image_path: "assets/icon/icon.png"

flutter_native_splash:
  color: "#e44641"
  image: "assets/splash/splash_icon.png"
  branding: "assets/splash/light_splash_logo.png"
  color_dark: "#2a2a2a"
  image_dark: "assets/splash/splash_icon.png"
  branding_dark: "assets/splash/dark_splash_logo.png"
  android_12:
    color: "#e44641"
    icon_background_color: "#e44641"
    image: "assets/splash/a12_splash_icon.png"
    branding: "assets/splash/a12_light_splash_logo.png"
    color_dark: "#2a2a2a"
    icon_background_color_dark: "#2a2a2a"
    image_dark: "assets/splash/a12_splash_icon.png"
    branding_dark: "assets/splash/a12_dark_splash_logo.png"
  android: true
  ios: true
  web: true

flutter:
  uses-material-design: true

  assets:
    - ".env"
    - "assets/svg/icon.svg"
    - "assets/svg/logo.svg"
    - "assets/svg/house.svg"
    - "assets/svg/house-fill.svg"
    - "assets/svg/heart.svg"
    - "assets/svg/heart-fill.svg"
    - "assets/svg/map-marker.svg"
    - "assets/svg/map-marker-fill.svg"
    - "assets/svg/user.svg"
    - "assets/svg/user-fill.svg"
    - "assets/svg/qr.svg"
    - "assets/svg/bell.svg"
    - "assets/svg/search.svg"
    - "assets/svg/empty-set.svg"
    - "assets/svg/face-sad-sweat.svg"
    - "assets/svg/croissant.svg"
    - "assets/svg/cup-straw-swoosh.svg"
    - "assets/svg/french-fries.svg"
    - "assets/svg/glass-cheers.svg"
    - "assets/svg/hamburger-soda.svg"
    - "assets/svg/mug-hot-alt.svg"
    - "assets/svg/restaurant.svg"
    - "assets/svg/instagram.svg"
    - "assets/svg/mail.svg"
    - "assets/svg/phone.svg"
    - "assets/svg/telegram.svg"
    - "assets/svg/whatsapp.svg"
    - "assets/svg/shopping-basket.svg"
    - "assets/svg/shopping-basket-fill.svg"
    - "assets/svg/list.svg"
    - "assets/svg/time-past.svg"
    - "assets/svg/shield-check.svg"
    - "assets/svg/interrogation.svg"
    - "assets/svg/comment-info.svg"
    - "assets/svg/som.svg"
    - "assets/svg/menu-food.svg"
    - "assets/svg/share.svg"
    - "assets/svg/sign-in.svg"
    - "assets/svg/google.svg"
    - "assets/svg/apple.svg"

    - "assets/icon/icon.png"

    - "assets/splash/a12_splash_icon.png"
    - "assets/splash/a12_dark_splash_logo.png"
    - "assets/splash/a12_light_splash_logo.png"
    - "assets/splash/splash_icon.png"
    - "assets/splash/dark_splash_logo.png"
    - "assets/splash/light_splash_logo.png"

    - "assets/placeholder/establishment.png"
    - "assets/placeholder/product.png"
    - "assets/placeholder/category.png"
    - "assets/placeholder/default.png"

  fonts:
    - family: Manrope
      fonts:
        - asset: "assets/fonts/Manrope/Manrope-ExtraBold.ttf"
          weight: 800
        - asset: "assets/fonts/Manrope/Manrope-Bold.ttf"
          weight: 700
        - asset: "assets/fonts/Manrope/Manrope-SemiBold.ttf"
          weight: 600
        - asset: "assets/fonts/Manrope/Manrope-Medium.ttf"
          weight: 500
        - asset: "assets/fonts/Manrope/Manrope-Regular.ttf"
          weight: 400
        - asset: "assets/fonts/Manrope/Manrope-Light.ttf"
          weight: 300
        - asset: "assets/fonts/Manrope/Manrope-ExtraLight.ttf"
          weight: 200
